version: '3.8'

services:
  backend:
    build:
      context: ./backend 
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/app  
      - ./backend/kitties.db:/app/kitties.db  
    environment:
      - DATABASE_URL=sqlite:///app/kitties.db  
    restart: always

  frontend:
    build:
      context: ./frontend  
    ports:
      - "3000:80"  
    restart: always

